/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Main "Guides" sidebar - tutorial + language + concepts + howtos
  guideSidebar: [
    {
      type: "doc",
      id: "index",
      label: "Overview",
    },
    {
      type: "category",
      label: "Tutorial",
      collapsed: false,
      items: [
        "tutorial/tutorial-index",
        "language/getting-started",
      ],
    },
    {
      type: "category",
      label: "Language (v1)",
      collapsed: false,
      items: [
        "language/index",
        "language/grammar",
        "language/app-config",
        "language/agents",
        "language/tools",
        "language/04b-builtin-tools",
        "language/04c-primitives",
        "language/04d-mcp",
        "language/output-channels",
        "language/memory",
        "language/context-management",
        "language/flows",
        "language/macros",
        "language/triggers",
        "language/expressions",
        "language/security",
        "language/multi-agent",
        "language/api-integration",
        "language/examples",
        "language/app-as-mcp-server",
        "language/middleware",
        "language/web",
        "language/skills",
        "language/auth",
        "language/composition",
        "language/configuration",
        "language/observability",
        "language/27-lsp",
        "language/31-tool-hooks",
        "language/33-rules",
        "language/sandbox",
        "language/production",
        "language/rag",
        "language/background-sessions",
        "language/bundle-namespaces",
        "language/channels",
        "language/workspace-preview",
        "language/widgets",
        "language/behavior",
        "language/client-manifest",
        "language/multi-tenant",
        "language/dev-cli",
        "language/preview-sdk",
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: true,
      items: [
        "concepts/concepts-index",
        "concepts/app-packages",
        "concepts/preview",
        "concepts/widgets",
        "concepts/glossary",
      ],
    },
    {
      type: "category",
      label: "How-tos",
      collapsed: true,
      items: [
        "howtos/howtos-index",
        "howtos/add-a-module",
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsed: true,
      items: [
        "examples/examples-index",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsed: true,
      items: [
        "deployment/deployment-index",
        "deployment/cloud-preview",
      ],
    },
    {
      type: "doc",
      id: "versioning",
      label: "Versioning",
    },
  ],

  // Reference sidebar - everything under reference/
  modulesSidebar: [
    {
      type: "doc",
      id: "reference/reference-index",
      label: "Reference",
    },
    {
      type: "category",
      label: "Modules",
      collapsed: false,
      items: [
        "reference/modules/modules-index",
        "reference/modules/agent_spawn",
        "reference/modules/behavior",
        "reference/modules/channels",
        "reference/modules/context_builder",
        "reference/modules/cron_native",
        "reference/modules/database",
        "reference/modules/dev_tools",
        "reference/modules/filesystem",
        "reference/modules/http",
        "reference/modules/index-module",
        "reference/modules/llm_provider",
        "reference/modules/lsp",
        "reference/modules/mcp",
        "reference/modules/memory",
        "reference/modules/preview",
        "reference/modules/queue",
        "reference/modules/rag",
        "reference/modules/shell",
        "reference/modules/vector",
        "reference/modules/web",
        "reference/modules/web_preview",
        "reference/modules/widget",
        "reference/modules/workspace",
      ],
    },
    {
      type: "category",
      label: "Runtime",
      collapsed: true,
      items: [
        "reference/runtime/runtime-index",
        "reference/runtime/configuration",
        "reference/runtime/credentials",
        "reference/runtime/hooks",
        "reference/runtime/middleware",
        "reference/runtime/multimodal",
        "reference/runtime/voice",
        "reference/runtime/tool-chaining",
      ],
    },
    {
      type: "category",
      label: "API",
      collapsed: true,
      items: [
        "reference/api/api-index",
        "reference/api/rest",
        "reference/api/socketio",
        "reference/api/dap",
      ],
    },
    {
      type: "category",
      label: "CLI",
      collapsed: true,
      items: [
        "reference/cli/cli-index",
      ],
    },
    {
      type: "category",
      label: "Client SDKs",
      collapsed: true,
      items: [
        "reference/client-sdks/client-sdks-index",
        "reference/client-sdks/flutter_socketio_integration",
        "reference/client-sdks/python-testing",
        "reference/client-sdks/web",
      ],
    },
  ],
};

module.exports = sidebars;
