"""MasterKeyProvider protocol + shared types.

Two operational modes are supported:

1. **Direct master key** (`wraps_data_key=False`): the provider returns
   a raw 32-byte AES-256 key. The cipher uses it directly for all
   encrypt/decrypt operations. Simplest, fastest, but the master key
   sits in process memory for the lifetime of the daemon.

   Used by: `EnvKeyProvider`, `FileKeyProvider`.

2. **Envelope encryption** (`wraps_data_key=True`): the provider holds
   a key on a remote KMS that NEVER leaves the KMS. The cipher
   generates a per-record DEK (Data Encryption Key) on the fly,
   encrypts the credential locally, then calls
   `provider.wrap_data_key(dek)` to get the wrapped (encrypted) DEK
   back from the KMS. On decrypt, the cipher hands the wrapped DEK
   back to `provider.unwrap_data_key(...)` to recover the plain DEK
   and decrypt the credential.

   The master key never appears in the daemon process. Auditable, key
   rotation handled by the KMS, IAM controls who can decrypt.

   Used by: `AwsKmsProvider`, `GcpKmsProvider`, `AzureKeyVaultProvider`,
   `VaultTransitProvider`.

Both modes implement the same interface so the cipher (`VersionedCipher`)
picks at runtime via `provider.wraps_data_key`.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Protocol, runtime_checkable


class KmsBackend(str, Enum):
    """Identifier of the backend used. Persisted alongside ciphertext
    so we know how to decrypt on read - and so a future migration from
    `env` to `aws_kms` doesn't break old rows."""

    ENV = "env"
    FILE = "file"
    AWS_KMS = "aws_kms"
    GCP_KMS = "gcp_kms"
    AZURE_KV = "azure_kv"
    VAULT = "vault"


@dataclass(frozen=True)
class KeyMaterial:
    """Data flowing between cipher and provider.

    Direct mode:
      - `data_key` is the raw 32-byte key used for AES-GCM.
      - `wrapped_dek` is None.

    Envelope mode:
      - `data_key` is a freshly generated 32-byte DEK (per record).
      - `wrapped_dek` is the KMS-wrapped form persisted alongside the
        ciphertext.
    """

    data_key: bytes
    wrapped_dek: bytes | None = None
    backend: KmsBackend = KmsBackend.ENV
    key_id: str | None = None  # KMS key ARN/URN for audit trail


class UnwrapFailed(Exception):
    """KMS refused to unwrap a wrapped DEK. Possible causes:
      - wrapped DEK was generated by a different KMS key (rotated)
      - IAM denial / network failure
      - tampered ciphertext

    The caller should treat this as an unrecoverable read error for
    that specific row - other rows may still be readable.
    """


class NoSuchProvider(Exception):
    """Raised by `build_provider_from_config` when the requested
    `DIGITORN_KMS` value doesn't match any registered backend."""


@runtime_checkable
class MasterKeyProvider(Protocol):
    """Uniform interface for every master-key source.

    Implementations either:
      - hold a 32-byte key in memory and expose it via `get_data_key()`
      - hold no key locally; rely on the remote KMS for wrap/unwrap
        (envelope mode).

    A daemon initialises ONE provider at boot and passes it to the
    `VersionedCipher`. The cipher decides the operational mode based
    on `provider.wraps_data_key`.
    """

    @property
    def backend(self) -> KmsBackend:
        """Which backend identifier to persist alongside ciphertext."""
        ...

    @property
    def wraps_data_key(self) -> bool:
        """When True, the cipher uses envelope mode: generate per-record
        DEK + ask the provider to wrap/unwrap. When False, the cipher
        uses the same data key for every record."""
        ...

    @property
    def key_id(self) -> str | None:
        """Identifier of the master key, for audit. KMS providers
        return the key ARN/URN; local providers return None or a
        sentinel like 'env' / 'file:~/.digitorn/master.key'."""
        ...

    async def get_data_key(self) -> KeyMaterial:
        """Return the data key to use for encryption.

        Direct mode: returns the master key itself (cached).
        Envelope mode: generates a fresh per-record DEK and wraps it
        with the KMS - the wrapped form is included in the result so
        the caller can persist it.
        """
        ...

    async def unwrap_data_key(self, wrapped: bytes) -> KeyMaterial:
        """Recover the plain DEK from its wrapped form.

        Direct mode: ignores `wrapped` (it should be None on read in
        direct mode) and returns the cached master key.
        Envelope mode: calls the KMS to decrypt the DEK.

        Raises `UnwrapFailed` if the KMS refuses (rotation, IAM,
        tampered).
        """
        ...

    async def healthcheck(self) -> bool:
        """Lightweight probe: is the backend reachable + the key
        accessible? Called at boot and periodically by the daemon to
        surface KMS misconfiguration before a credential request blows
        up. Returns True on success, False on any failure (no exception
        - caller decides severity)."""
        ...

    async def close(self) -> None:
        """Release any resources held by the provider (HTTP clients,
        KMS sessions). Called at daemon shutdown."""
        ...

    def get_data_key_sync(self) -> KeyMaterial:
        """Synchronous variant for direct-mode providers (env/file).

        KMS-backed providers MUST raise `NotImplementedError` so callers
        know they cannot call this from sync contexts. This method
        exists so the legacy sync `CredentialStore` path keeps working
        with the new versioned cipher when no KMS is configured.
        """
        raise NotImplementedError(
            "get_data_key_sync is only available on direct-mode providers"
        )

    def unwrap_data_key_sync(self, wrapped: bytes) -> KeyMaterial:
        """Synchronous variant of `unwrap_data_key`. Same contract as
        `get_data_key_sync`."""
        raise NotImplementedError(
            "unwrap_data_key_sync is only available on direct-mode providers"
        )
