"""Base channel adapter — bidirectional I/O contract.

Extends ``BaseOutputChannel`` (outbound) with inbound listener capabilities.
Existing output-only channels remain compatible; adapters that only need outbound
can ignore the inbound methods.

Security invariants:
- ``validate_inbound()`` is called BEFORE payload parsing.
- ``max_inbound_payload_bytes()`` enforces a hard size limit at the raw byte level.
- ``reply_context`` is always constructed by the adapter from verified data,
  never from raw user input.
"""

from __future__ import annotations

import time
import uuid
from abc import abstractmethod
from dataclasses import dataclass, field
from typing import Any, Awaitable, Callable

from digitorn.core.app.channels.base import (
    BaseOutputChannel,
    ChannelCapabilities,
    ChannelPayload,
    DeliveryResult,
)


# ── Inbound event ────────────────────────────────────────────────────


@dataclass(frozen=True)
class InboundEvent:
    """Normalized inbound event from any channel adapter.

    Produced by adapters, consumed by the activation pipeline.
    Immutable (frozen) — the pipeline never mutates the original event.

    Attributes:
        event_id:       Unique ID for idempotency (generated by adapter).
        provider_id:    Instance name from YAML ``providers:`` block.
        adapter_type:   Adapter type (``webhook``, ``cron``, ``email``, …).
        source:         Sender identifier (phone number, email, IP, cron expr).
        message:        Text content (if applicable — empty for webhooks).
        payload:        Sanitized structured data from the source.
        metadata:       Adapter-specific metadata (headers, attachments, etc.).
        timestamp:      Unix timestamp of event arrival.
        reply_context:  Opaque dict for ``reply:auto``. Built by the adapter
                        from *verified* fields only — never user-controllable.
    """

    event_id: str
    provider_id: str
    adapter_type: str
    source: str
    message: str = ""
    payload: dict[str, Any] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=time.time)
    reply_context: dict[str, Any] = field(default_factory=dict)


def make_event_id() -> str:
    """Generate a unique, URL-safe event ID."""
    return f"evt-{uuid.uuid4().hex[:16]}"


# ── Adapter capabilities extension ───────────────────────────────────


@dataclass
class AdapterCapabilities(ChannelCapabilities):
    """Extended capabilities declaring inbound + outbound support."""

    supports_inbound: bool = False
    supports_outbound: bool = True
    supports_streaming: bool = False
    supports_reactions: bool = False


# ── Callback type ────────────────────────────────────────────────────

InboundCallback = Callable[[InboundEvent], Awaitable[None]]


# ── Base adapter ─────────────────────────────────────────────────────


class BaseChannelAdapter(BaseOutputChannel):
    """Bidirectional channel adapter.

    Extends ``BaseOutputChannel`` with inbound listener methods.
    Adapters that are outbound-only can skip the inbound overrides —
    ``start_listener`` defaults to a no-op.

    Security contract:
    - ``validate_inbound()`` is called before JSON parsing on raw bytes.
    - ``max_inbound_payload_bytes()`` returns the hard byte-size limit.
    - ``send_reply()`` uses only the ``reply_context`` built by the adapter.
    """

    # Override in subclasses
    SUPPORTS_INBOUND: bool = False
    SUPPORTS_OUTBOUND: bool = True

    # ── Inbound lifecycle ────────────────────────────────────────

    async def start_listener(self, callback: InboundCallback) -> None:
        """Start listening for inbound events.

        The adapter calls ``callback(event)`` for each incoming event.
        Must be non-blocking — use ``asyncio.create_task`` internally.

        Default: no-op (outbound-only adapters).
        """

    async def stop_listener(self) -> None:
        """Stop the inbound listener and release resources.

        Default: no-op.
        """

    # ── Inbound security ─────────────────────────────────────────

    async def validate_inbound(
        self,
        raw_body: bytes,
        headers: dict[str, str],
    ) -> tuple[bool, str]:
        """Validate an inbound request BEFORE parsing.

        Called by the webhook route handler with raw bytes and headers.
        Implementations should:
        1. Verify HMAC signature (if configured).
        2. Check Content-Type whitelist.
        3. Reject payloads exceeding ``max_inbound_payload_bytes()``.

        Returns:
            (is_valid, error_message). error_message is empty on success.
        """
        return True, ""

    def max_inbound_payload_bytes(self) -> int:
        """Hard limit on inbound payload size in bytes.

        Checked at the raw byte level BEFORE JSON parsing to prevent
        memory exhaustion. Default: 1 MB.
        """
        return 1_048_576  # 1 MB

    # ── Outbound reply ───────────────────────────────────────────

    async def send_reply(
        self,
        reply_context: dict[str, Any],
        text: str,
        payload: ChannelPayload | None = None,
    ) -> DeliveryResult:
        """Send a reply using the context from an inbound event.

        Used by ``reply: auto`` in the activation pipeline.
        The ``reply_context`` is the opaque dict from ``InboundEvent``,
        built by *this adapter* from verified inbound data.

        Default: delegates to ``deliver()`` with reply_context as config.
        Override for channel-specific reply semantics (threading, etc.).
        """
        effective_payload = payload or ChannelPayload(message=text)
        config = dict(reply_context)
        return await self.deliver(
            app_id=config.pop("_app_id", ""),
            payload=effective_payload,
            config=config,
        )

    # ── Extended capabilities ────────────────────────────────────

    def adapter_capabilities(self) -> AdapterCapabilities:
        """Return full adapter capabilities (inbound + outbound)."""
        base = self.capabilities()
        return AdapterCapabilities(
            supports_inbound=self.SUPPORTS_INBOUND,
            supports_outbound=self.SUPPORTS_OUTBOUND,
            supports_rich_text=base.supports_rich_text,
            supports_attachments=base.supports_attachments,
            supports_threading=base.supports_threading,
            supports_batching=base.supports_batching,
            max_message_length=base.max_message_length,
            max_attachment_bytes=base.max_attachment_bytes,
            supported_formats=base.supported_formats,
        )
