"""Purge orphan test apps from the daemon DB.

Problem: every test that calls `DELETE /api/apps/{id}` returns 2xx but
doesn't actually remove the DB row (see docs/RULES_MATRIX.md → note on
`delete_app`). After hundreds of test runs, `reload_from_db` at daemon
startup spends minutes compiling + auto-starting 174 zombie apps whose
bundles on disk were already deleted.

This script surgically removes ONLY rows matching a known-test pattern
AND whose bundle dir is missing on disk. Legitimate apps
(`digitorn-chat`, `opencode`, `my-assistant`, etc.) are never touched.

Usage:
    py -3.12 tools/cleanup_orphan_apps.py            # dry-run (default)
    py -3.12 tools/cleanup_orphan_apps.py --yes      # actually delete

Exit code: 0 on success, non-zero on error.
"""
from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from pathlib import Path

# Only target app_ids matching these prefixes (safe to delete — they're
# ours, generated by the test harnesses).
_TEST_PATTERNS = [
    re.compile(r"^smoke-"),
    re.compile(r"^force-"),
    re.compile(r"^db-test-"),
    re.compile(r"^test-force-"),
    re.compile(r"^e2e-"),
    re.compile(r"^multi$"),
    re.compile(r"^jobhunt$"),
]


def is_test_pattern(app_id: str) -> bool:
    return any(rx.match(app_id) for rx in _TEST_PATTERNS)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db",
                    default=str(Path("digitorn.db").resolve()),
                    help="Path to the daemon's SQLite DB (default: ./digitorn.db)")
    ap.add_argument("--bundles-root",
                    default=str(Path.home() / ".digitorn" / "apps"),
                    help="Bundle store root (default: ~/.digitorn/apps)")
    ap.add_argument("--yes", action="store_true",
                    help="Actually delete. Without this, runs in dry-run mode.")
    args = ap.parse_args()

    db_path = Path(args.db)
    bundles_root = Path(args.bundles_root)
    if not db_path.exists():
        print(f"FATAL: DB not found at {db_path}")
        return 1
    print(f"DB:      {db_path}  ({db_path.stat().st_size // 1024} KB)")
    print(f"Bundles: {bundles_root}\n")

    conn = sqlite3.connect(str(db_path))
    cur = conn.cursor()
    cur.execute("SELECT app_id FROM applications ORDER BY app_id")
    all_apps = [r[0] for r in cur.fetchall()]

    candidates: list[str] = []
    safe_skip: list[str] = []
    for app_id in all_apps:
        if not is_test_pattern(app_id):
            safe_skip.append(app_id)
            continue
        bundle_dir = bundles_root / app_id
        if bundle_dir.exists():
            # Bundle still on disk — don't touch. User may want it.
            safe_skip.append(app_id)
            continue
        candidates.append(app_id)

    print(f"Legitimate apps (skipped): {len(safe_skip)}")
    for a in safe_skip:
        print(f"  keep   {a}")
    print(f"\nOrphan test apps (no bundle on disk): {len(candidates)}")
    for a in candidates[:20]:
        print(f"  purge  {a}")
    if len(candidates) > 20:
        print(f"  ... ({len(candidates) - 20} more)")

    if not candidates:
        print("\nNothing to clean.")
        return 0

    if not args.yes:
        print(f"\nDRY RUN. Re-run with --yes to actually remove "
              f"{len(candidates)} row(s) from `applications` and the cascading tables.")
        return 0

    # Cascade-delete across all related tables. Order matters because
    # of FK relationships. We do this in a single transaction.
    # (table, column_holding_app_id). Not every related table has an
    # `app_id` column directly — some use a FK to another table (e.g.
    # session_messages.session_pk → user_sessions.id). Cleaning those
    # cascades is SQLAlchemy's job via its relationships, not ours.
    # For our one-off purge we target only the tables that *directly*
    # hold the app_id — enough to eliminate the reload_from_db load.
    related_tables = [
        ("app_profiles",       "app_id"),
        ("app_module_configs", "app_id"),
        ("app_secrets",        "app_id"),
        ("app_bundles",        "app_id"),
        ("activations",        "app_id"),
        ("background_sessions","app_id"),
        ("user_sessions",      "app_id"),
        ("session_checkpoints","app_id"),
        ("action_executions",  "app_id"),
        ("usage_events",       "app_id"),
    ]

    # Confirm which related tables actually exist in this schema.
    cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
    existing_tables = {r[0] for r in cur.fetchall()}
    related_tables = [(t, c) for t, c in related_tables if t in existing_tables]

    try:
        cur.execute("BEGIN")
        # Break the FK back-reference on applications before deleting bundles.
        for app_id in candidates:
            cur.execute(
                "UPDATE applications SET current_bundle_id = NULL WHERE app_id = ?",
                (app_id,),
            )
        for tbl, col in related_tables:
            placeholders = ",".join("?" for _ in candidates)
            cur.execute(
                f"DELETE FROM {tbl} WHERE {col} IN ({placeholders})",
                candidates,
            )
        placeholders = ",".join("?" for _ in candidates)
        cur.execute(
            f"DELETE FROM applications WHERE app_id IN ({placeholders})",
            candidates,
        )
        conn.commit()
    except Exception as exc:
        conn.rollback()
        print(f"\nFAILED, transaction rolled back: {exc}")
        return 2

    print(f"\n✓ Deleted {len(candidates)} orphan app(s) "
          f"and their cascading rows in {len(related_tables)} related tables.")
    print("Restart the daemon to observe a fast, clean startup.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
